%YAML:1.0
calibration_time: "Tue Jan 12 15:27:31 2016"
image_width: 640
image_height: 480
board_width: 7
board_height: 7
square_size: 0.0625
flags: 0
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [381.36246688113556, 0.0, 320.5, 0.0, 381.36246688113556, 240.5, 0.0, 0.0, 1.0]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]